package com.company.aitest.workflow;

public enum TaskStatus {
    CREATED,
    REQUIREMENT_ANALYZING,
    RETRIEVAL_PLANNING,
    KNOWLEDGE_RETRIEVING,
    IMPACT_ANALYZING,
    CLARIFYING_REQUIREMENT,
    TEST_POINT_GENERATING,
    TEST_POINT_REVIEWING,
    TEST_CASE_GENERATING,
    TEST_CASE_REVIEWING,
    QUALITY_CHECKING,
    FINAL_CONFIRMING,
    EXPORTING,
    ASSET_PERSISTING,
    COMPLETED,
    PAUSED,
    CANCELLED,
    FAILED
}
