package com.company.aitest.workflow;

public enum WorkflowEvent {
    START,
    ANALYSIS_DONE,
    RETRIEVAL_PLAN_DONE,
    KNOWLEDGE_RETRIEVED,
    IMPACT_ANALYZED,
    CLARIFICATION_ENDED,
    TEST_POINTS_GENERATED,
    TEST_POINTS_REVIEWED,
    TEST_CASES_GENERATED,
    TEST_CASES_REVIEWED,
    QUALITY_CHECKED,
    FINAL_CONFIRMED,
    EXPORTED,
    ASSET_PERSISTED,
    CANCEL,
    FAIL,
    PAUSE
}
