CREATE TABLE worker_device (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    device_name VARCHAR(128) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    arch VARCHAR(32) NOT NULL,
    worker_version VARCHAR(32) NOT NULL,
    protocol_version VARCHAR(32) NOT NULL,
    bind_status VARCHAR(32) NOT NULL,
    worker_token_hash VARCHAR(128),
    last_seen_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_worker_user (user_id),
    INDEX idx_worker_status (bind_status),
    INDEX idx_worker_last_seen (last_seen_at)
);

CREATE TABLE browser_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    profile_name VARCHAR(128) NOT NULL,
    target_host VARCHAR(255),
    account_label VARCHAR(128),
    role_label VARCHAR(128),
    storage_state_path VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_used_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_profile_project_user (project_id, user_id),
    INDEX idx_profile_user (user_id),
    INDEX idx_profile_status (status),
    INDEX idx_profile_created (created_at)
);

CREATE TABLE browser_profile_operation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    profile_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operation_detail TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_profile_operation (profile_id),
    INDEX idx_profile_operation_user (user_id),
    INDEX idx_profile_operation_created (created_at)
);

CREATE TABLE browser_trace_group (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    started_at DATETIME,
    stopped_at DATETIME,
    timezone VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_trace_group_project (project_id),
    INDEX idx_trace_group_user (user_id),
    INDEX idx_trace_group_status (status),
    INDEX idx_trace_group_created (created_at)
);

CREATE TABLE browser_trace_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_group_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    session_name VARCHAR(255),
    browser_type VARCHAR(64),
    browser_executable_path VARCHAR(512),
    video_path VARCHAR(512),
    trace_file_path VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'RECORDING',
    recording_started_at_utc DATETIME,
    recording_started_at_local DATETIME,
    recording_stopped_at_utc DATETIME,
    recording_stopped_at_local DATETIME,
    timezone VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_trace_session_group (trace_group_id),
    INDEX idx_trace_session_project (project_id),
    INDEX idx_trace_session_user (user_id),
    INDEX idx_trace_session_profile (profile_id),
    INDEX idx_trace_session_status (status),
    INDEX idx_trace_session_created (created_at)
);

CREATE TABLE browser_trace_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_group_id BIGINT NOT NULL,
    trace_session_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    page_url VARCHAR(2048),
    page_title VARCHAR(512),
    element_text VARCHAR(512),
    element_role VARCHAR(128),
    selector TEXT,
    value_summary TEXT,
    screenshot_path VARCHAR(512),
    happened_at_utc DATETIME NOT NULL,
    happened_at_local DATETIME NOT NULL,
    timezone VARCHAR(64),
    relative_ms BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_trace_event_session_time (trace_session_id, relative_ms),
    INDEX idx_trace_event_group_time (trace_group_id, relative_ms),
    INDEX idx_trace_event_profile (profile_id),
    INDEX idx_trace_event_type (event_type),
    INDEX idx_trace_event_created (created_at)
);

CREATE TABLE browser_trace_network (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_group_id BIGINT NOT NULL,
    trace_session_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    url VARCHAR(2048) NOT NULL,
    method VARCHAR(16),
    status_code INT,
    duration_ms BIGINT,
    failed TINYINT NOT NULL DEFAULT 0,
    error_message TEXT,
    request_summary TEXT,
    response_summary TEXT,
    request_started_at_utc DATETIME,
    request_started_at_local DATETIME,
    response_ended_at_utc DATETIME,
    response_ended_at_local DATETIME,
    timezone VARCHAR(64),
    relative_ms BIGINT,
    created_at DATETIME NOT NULL,
    INDEX idx_trace_network_session_time (trace_session_id, relative_ms),
    INDEX idx_trace_network_group_time (trace_group_id, relative_ms),
    INDEX idx_trace_network_profile (profile_id),
    INDEX idx_trace_network_failed (failed),
    INDEX idx_trace_network_created (created_at)
);

CREATE TABLE browser_issue_clip (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_group_id BIGINT NOT NULL,
    trace_session_id BIGINT,
    profile_id BIGINT,
    clip_scope VARCHAR(32) NOT NULL COMMENT 'SESSION/GROUP',
    title VARCHAR(255),
    description TEXT,
    clip_start_at_utc DATETIME NOT NULL,
    clip_start_at_local DATETIME NOT NULL,
    clip_end_at_utc DATETIME NOT NULL,
    clip_end_at_local DATETIME NOT NULL,
    clip_start_relative_ms BIGINT NOT NULL,
    clip_end_relative_ms BIGINT NOT NULL,
    timezone VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_issue_clip_group (trace_group_id),
    INDEX idx_issue_clip_session (trace_session_id),
    INDEX idx_issue_clip_profile (profile_id),
    INDEX idx_issue_clip_status (status),
    INDEX idx_issue_clip_created_by (created_by),
    INDEX idx_issue_clip_created (created_at)
);

CREATE TABLE trace_generated_case (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    trace_group_id BIGINT,
    trace_session_id BIGINT,
    issue_clip_id BIGINT,
    case_type VARCHAR(64) NOT NULL,
    case_title VARCHAR(255),
    module_name VARCHAR(255),
    precondition TEXT,
    steps TEXT,
    expected_result TEXT,
    priority VARCHAR(16),
    case_scope VARCHAR(32) NOT NULL DEFAULT 'PERSONAL',
    case_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    source_refs_json TEXT,
    model_config_id BIGINT,
    prompt_snapshot LONGTEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_trace_case_user (project_id, user_id),
    INDEX idx_trace_case_group (trace_group_id),
    INDEX idx_trace_case_session (trace_session_id),
    INDEX idx_trace_case_clip (issue_clip_id),
    INDEX idx_trace_case_status (case_status),
    INDEX idx_trace_case_created (created_at)
);

CREATE TABLE knowledge_asset (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    asset_type VARCHAR(64) NOT NULL,
    asset_ref_type VARCHAR(64) NOT NULL,
    asset_ref_id BIGINT NOT NULL,
    title VARCHAR(255),
    content LONGTEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    created_by BIGINT,
    deprecated_by BIGINT,
    deprecated_at DATETIME,
    deprecated_reason VARCHAR(64),
    deprecated_note TEXT,
    is_vectorized TINYINT NOT NULL DEFAULT 0,
    vector_id VARCHAR(128),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_asset_project_status (project_id, status),
    INDEX idx_asset_ref (asset_ref_type, asset_ref_id),
    INDEX idx_asset_created_by (created_by),
    INDEX idx_asset_created (created_at)
);

CREATE TABLE asset_tag (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    tag_name VARCHAR(64) NOT NULL,
    tag_type VARCHAR(32) NOT NULL COMMENT 'SYSTEM/USER',
    created_by BIGINT,
    created_at DATETIME NOT NULL,
    INDEX idx_asset_tag_project_type (project_id, tag_type),
    UNIQUE KEY uk_asset_tag (project_id, tag_name)
);

CREATE TABLE asset_tag_relation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    created_by BIGINT,
    created_at DATETIME NOT NULL,
    INDEX idx_tag_relation_target (target_type, target_id),
    UNIQUE KEY uk_tag_relation (tag_id, target_type, target_id)
);

CREATE TABLE test_skill_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    skill_name VARCHAR(255) NOT NULL,
    applicable_scene TEXT,
    flow_steps TEXT,
    source_type VARCHAR(64),
    source_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    deprecated_reason VARCHAR(64),
    is_vectorized TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_skill_project_status (project_id, status),
    INDEX idx_skill_created_by (created_by),
    INDEX idx_skill_created (created_at)
);

CREATE TABLE test_tool_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    operation_steps TEXT,
    source_type VARCHAR(64),
    source_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    deprecated_reason VARCHAR(64),
    is_vectorized TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_tool_project_status (project_id, status),
    INDEX idx_tool_created_by (created_by),
    INDEX idx_tool_created (created_at)
);

ALTER TABLE test_case_asset
    MODIFY COLUMN source_task_id BIGINT NULL,
    MODIFY COLUMN source_draft_id BIGINT NULL,
    ADD COLUMN case_scope VARCHAR(32) NOT NULL DEFAULT 'PROJECT',
    ADD COLUMN case_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN submitted_by BIGINT,
    ADD COLUMN submitted_at DATETIME,
    ADD COLUMN exported_at DATETIME,
    ADD COLUMN source_trace_group_id BIGINT,
    ADD COLUMN source_trace_session_id BIGINT,
    ADD COLUMN source_issue_clip_id BIGINT,
    ADD INDEX idx_case_asset_scope_status (case_scope, case_status),
    ADD INDEX idx_case_asset_submitted (submitted_by, submitted_at),
    ADD INDEX idx_case_asset_trace_group (source_trace_group_id),
    ADD INDEX idx_case_asset_trace_session (source_trace_session_id),
    ADD INDEX idx_case_asset_issue_clip (source_issue_clip_id);
